sudo: false
language: ruby
services:
  - docker
before_install:
  - git clone --depth 1 https://github.com/seiferma/Docker_BuildUtils.git /tmp/BuildUtils
  - . /tmp/BuildUtils/travisSetup.sh
script:
  - travisBuildDockerhub.sh
deploy:
  provider: script
  script: travisDeployDockerhub.sh
  on:
    branch: master
env:
  global: 
    - IMAGE_NAME=seiferma/plexmediaserver
    - secure: "IzbKijC5gsupX+vUk9/Bda29fx0cy6wuSz3C4UmQcbGkJ9cewhKh4QpoPCItUCqq9B88RCjLwq5OJzGRIAC/NyZt4l2J/zgmf8jexuPT/eC2pmthEYGB9Ckg4SwBfp33JkZ5yaOooVY6EB2ueJLiSFJbOR93/hncTbVkQQ11S9XHFPfyA45Dl8f2m3G7pr2vXI6h0JF9IM/iQFU1vkjkjBRIHNMD8l4vPu4TJiIeJJMkI3QN6Au+iC1Qu3KjhX2x5gLTf2zv1lwZ79J/V4u1zwAs2UvskOxl2Zs4LuSeyS2x/jUjFJm0qqLvgZfgwBzavqOaAGpUZu01OCO2XzCRLnwRTD7fkHK4MnSYPZAlYYIJ2Ak5Rj9RFfkT20d7FKEdDFLFfdKxiHHf25FfE7xOExxTMqR4XO+DMEx1tf8JhtSHQCSSMnl0CLAzliCblF9BC+ztTnegepzv+yJsLDjiT8UGuMmaCY/eALMdYEeVb8auOscuYIOxCKKURcSCfRTYibq/X520DrWDx857iVMgafJcKh/DaLJoMVgbcxnt2oJxvI7/oOUOXHnF1R6cGUUHssT5HIv6wajMFfzht0wIkDDaSWRkfDYUMpw7s0L4H9KJLp96WtLotAKmd/nh0VTzPNPuFTMEcGAR4VbVC2oMykkzOg8HSmjaJdqrrhcTXcA="